insert into fauna (name, avg_age, discovery_date) values ('Goldfish', 1, '1921-10-23');
insert into fauna (name, avg_age, discovery_date) values ('African wild dog', 59, '1937-08-22');
insert into fauna (name, avg_age, discovery_date) values ('Cobra, egyptian', 26, '1949-10-14');
insert into fauna (name, avg_age, discovery_date) values ('Dove, rock', 91, '1992-04-11');
insert into fauna (name, avg_age, discovery_date) values ('Carpet python', 62, '1980-06-02');
insert into fauna (name, avg_age, discovery_date) values ('Shrew, mandras tree', 25, '1922-01-07');
insert into fauna (name, avg_age, discovery_date) values ('Gray duiker', 46, '1916-06-22');
insert into fauna (name, avg_age, discovery_date) values ('Malachite kingfisher', 18, '1943-02-09');
insert into fauna (name, avg_age, discovery_date) values ('Tern, white-winged', 24, '1905-10-13');
insert into fauna (name, avg_age, discovery_date) values ('Duiker, common', 56, '1999-06-09');
insert into fauna (name, avg_age, discovery_date) values ('Guerza', 72, null);
insert into fauna (name, avg_age, discovery_date) values ('Porcupine, prehensile-tailed', 93, null);
insert into fauna (name, avg_age, discovery_date) values ('Red squirrel', 90, null);
insert into fauna (name, avg_age, discovery_date) values ('Gorilla, western lowland', 55, '1914-05-13');
insert into fauna (name, avg_age, discovery_date) values ('White-rumped vulture', 25, '1977-06-26');
insert into fauna (name, avg_age, discovery_date) values ('Frog (unidentified)', 15, '1985-08-22');
insert into fauna (name, avg_age, discovery_date) values ('Yellow-crowned night heron', 89, '1942-04-26');
insert into fauna (name, avg_age, discovery_date) values ('Vine snake (unidentified)', 62, '1914-09-11');
insert into fauna (name, avg_age, discovery_date) values ('Cheetah', 60, '1939-10-20');
insert into fauna (name, avg_age, discovery_date) values ('Rat, arboral spiny', 27, null);
insert into fauna (name, avg_age, discovery_date) values ('Civet cat', 48, '2015-12-15');
insert into fauna (name, avg_age, discovery_date) values ('Superb starling', 21, '1942-01-08');
insert into fauna (name, avg_age, discovery_date) values ('Boa, emerald green tree', 39, '2003-10-13');
insert into fauna (name, avg_age, discovery_date) values ('Darter, african', 87, '1973-05-26');
insert into fauna (name, avg_age, discovery_date) values ('Wallaby, agile', 60, '1992-10-05');
insert into fauna (name, avg_age, discovery_date) values ('Porcupine, african', 57, '1901-08-21');
insert into fauna (name, avg_age, discovery_date) values ('Brush-tailed rat kangaroo', 24, '1938-12-01');
insert into fauna (name, avg_age, discovery_date) values ('River wallaby', 5, '1992-11-28');
insert into fauna (name, avg_age, discovery_date) values ('Otter, north american river', 67, '2016-09-24');
insert into fauna (name, avg_age, discovery_date) values ('Squirrel, smith''s bush', 8, '1971-07-30');
insert into fauna (name, avg_age, discovery_date) values ('Vulture, turkey', 69, '1968-04-17');